version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123.password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
    ports:
      - '5433:5432'
  php:
    build: php-fpm
    ports:
      - '9002:9000'
    volumes:
      - ../case_study:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/logs:cached
    links:
      - postgres
  nginx:
    build: nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
